FROM node:26-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# El flag --host es vital en Docker para que Vite exponga el puerto hacia tu máquina local
CMD ["npm", "run", "dev", "--", "--host"]