FROM node:20-alpine
WORKDIR /usr/src/app
# Copiamos solo los archivos de dependencias primero para aprovechar el caché de Docker
COPY package*.json ./
RUN npm install
# Copiamos el resto del código
COPY . .
EXPOSE 4000
# Asumiendo que usarás node --watch o nodemon configurado en tu package.json
CMD ["npm", "run", "dev"]